### ISSUE TITLE
Remove referenced resource in shoot spec if additional DNS provider is deleted

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener-extension-shoot-dns-service#120]
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

If an additional DNS provider is added in the shoot spec like

```yaml
spec:  dns:
    domain: webhook-test.lukas.shoot.dev.k8s-hana.ondemand.com
    providers:
      - primary: false
        secretName: other-secret
        type: aws-route53
```

the mutating webhook of the shoot-dns-service extension adds a referenced resource:

```yaml
resources:
    - name: shoot-dns-service-other-secret
      resourceRef:
        kind: Secret
        name: other-secret
        apiVersion: v1
```

If the DNS provider is deleted, the referenced resource entry is not deleted and reconciliation fails if the secret is deleted.

**What you expected to happen**:

The mutating webhook should remove the referenced resource.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
