### ISSUE TITLE
Extension state exceeds the default request size limit of etcd when cluster has > 2000 DNSEntries

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-shoot-dns-service#413]
**How to categorize this issue?**

/area scalability
/kind enhancement

**What happened**:
Folks conducted a performance test for a Shoot cluster.

They deployed >13,000 DNSEntries as part of the test.

After ~2000 DNSEntries, the `shoot_dns_service_replication_controller` fails to maintain the DNSEntries in the Extension `.status.state.entries` field.
```
{"log":{"controller":"shoot_dns_service_replication_controller","error":"etcdserver: request is too large","level":"error","msg":"Reconciler error","name":"4e8a3eff-e5ad-4604-ba16-7a459bc5b618-app-dnsentry-v88f8","namespace":"shoot--cbc-multi--test-perf","object":{"name":"4e8a3eff-e5ad-4604-ba16-7a459bc5b618-app-dnsentry-v88f8","namespace":"shoot--cbc-multi--test-perf"},"reconcileID":"5340e62d-38f7-4848-bae5-4876857b536b","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.3/pkg/internal/controller/controller.go:224","ts":"2025-01-09T09:40:00.908Z"}}
```

gardenlet cannot update the Extension resource as well as part of the Shoot reconciliation:
```yaml
status:
  lastErrors:
    - description: "task \"Deploying extension resources after kube-apiserver\" failed: retry failed with context deadline exceeded, last error: 1 error occurred:\n\t* etcdserver: request is too large\n\n"
      taskID: Deploying extension resources after kube-apiserver
      lastUpdateTime: '2025-01-09T09:54:54Z'
```

Colleagues shared that every DNSEntry from the Shoot cluster is being maintained in the `.status.state.entries` field of the Extension object. 

We could try to improve by compressing the resources in the Extension state. @plkokanov shared an example where we use compression to store the machine states in the ShootState resource: https://github.com/gardener/gardener/blob/ab8ede5a1f38a643a4ab0d03b8c42d21ee9ef34b/pkg/utils/gardener/shootstate/shootstate.go#L129-L150

**What you expected to happen**:
No `etcdserver: request is too large` error caused when DNSEntries count > 2000.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
N/A

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.55.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
